name: FMCRules
main: hu.Pdani.FMCRules.FMCRulesPlugin
version: '1.3.0'
authors: [Pdani001]
description: FNaFMC rules plugin
softdepend: [Skript]
permissions:
  fmcrules.admin:
    description: Admin permission
    default: op