name: FMCRules
main: hu.Pdani.FMCRules.FMCRulesPlugin
version: '1.3.2'
authors: [Pdani001]
description: FNaFMC rules plugin
softdepend: [Skript,floodgate-bukkit]
permissions:
  fmcrules.admin:
    description: Admin permission
    default: op